[versions]
# libraries
junit = "4.13.2"
annotations = "26.0.2-1"

# plugins
kotlin = "2.3.0"
changelog = "2.5.0"
gradleIntelliJPlugin = "2.11.0"
qodana = "2025.3.1"
kover = "0.9.4"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij.platform", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
